/**
 * NPB 2026 シーズン試合スケジュール (yyyy-mm-dd → 対戦カードの配列)。
 *
 * データソース: NPB 公式日程 (https://npb.jp/games/2026/) — レギュラー
 * シーズン分のみ。10 月以降の CS / 日本シリーズはチーム確定後に手動で
 * 追加してください。
 *
 * 再取得方法: scripts/fetch-npb-schedule.mjs を走らせると最新の
 * HTML を取りに行って同形式 JSON を吐きます (依存ゼロの Node 22+ で可)。
 *
 * 各エントリのキーは JST 日付。値は `{ home, away }` の配列で、home は
 * ハンデを出している側 (主催チーム)、away は対戦相手。チーム名は
 * npbTeams.js の NPB_TEAMS_PRESET の name と完全一致。
 *
 * 雨天中止 / 休養日 / オールスター期間はキー自体を作らない方針
 * (gamesOn が空配列を返し、UI で「試合なし」表示)。
 */
export const NPB_SCHEDULE = Object.freeze({
  // ─── 3月 (開幕) ─────────────────────────────────────────────────────────
  "2026-03-27": [
    { home: "巨人", away: "阪神" },
    { home: "DeNA", away: "ヤクルト" },
    { home: "広島", away: "中日" },
    { home: "ロッテ", away: "西武" },
    { home: "オリックス", away: "楽天" },
    { home: "ソフトバンク", away: "日本ハム" },
  ],
  "2026-03-28": [
    { home: "巨人", away: "阪神" },
    { home: "DeNA", away: "ヤクルト" },
    { home: "広島", away: "中日" },
    { home: "ロッテ", away: "西武" },
    { home: "オリックス", away: "楽天" },
    { home: "ソフトバンク", away: "日本ハム" },
  ],
  "2026-03-29": [
    { home: "巨人", away: "阪神" },
    { home: "DeNA", away: "ヤクルト" },
    { home: "広島", away: "中日" },
    { home: "ロッテ", away: "西武" },
    { home: "オリックス", away: "楽天" },
    { home: "ソフトバンク", away: "日本ハム" },
  ],
  "2026-03-31": [
    { home: "ヤクルト", away: "広島" },
    { home: "中日", away: "巨人" },
    { home: "阪神", away: "DeNA" },
    { home: "日本ハム", away: "ロッテ" },
    { home: "楽天", away: "ソフトバンク" },
    { home: "西武", away: "オリックス" },
  ],

  // ─── 4月 ────────────────────────────────────────────────────────────────
  "2026-04-01": [
    { home: "中日", away: "巨人" },
    { home: "阪神", away: "DeNA" },
    { home: "日本ハム", away: "ロッテ" },
    { home: "楽天", away: "ソフトバンク" },
    { home: "西武", away: "オリックス" },
  ],
  "2026-04-02": [
    { home: "ヤクルト", away: "広島" },
    { home: "中日", away: "巨人" },
    { home: "阪神", away: "DeNA" },
    { home: "日本ハム", away: "ロッテ" },
    { home: "楽天", away: "ソフトバンク" },
    { home: "西武", away: "オリックス" },
  ],
  "2026-04-03": [
    { home: "巨人", away: "DeNA" },
    { home: "ヤクルト", away: "中日" },
    { home: "広島", away: "阪神" },
    { home: "日本ハム", away: "オリックス" },
    { home: "西武", away: "楽天" },
    { home: "ロッテ", away: "ソフトバンク" },
  ],
  "2026-04-04": [
    { home: "巨人", away: "DeNA" },
    { home: "ヤクルト", away: "中日" },
    { home: "広島", away: "阪神" },
    { home: "日本ハム", away: "オリックス" },
    { home: "西武", away: "楽天" },
    { home: "ロッテ", away: "ソフトバンク" },
  ],
  "2026-04-05": [
    { home: "巨人", away: "DeNA" },
    { home: "ヤクルト", away: "中日" },
    { home: "広島", away: "阪神" },
    { home: "日本ハム", away: "オリックス" },
    { home: "西武", away: "楽天" },
    { home: "ロッテ", away: "ソフトバンク" },
  ],
  "2026-04-07": [
    { home: "DeNA", away: "中日" },
    { home: "阪神", away: "ヤクルト" },
    { home: "広島", away: "巨人" },
    { home: "楽天", away: "日本ハム" },
    { home: "オリックス", away: "ロッテ" },
    { home: "ソフトバンク", away: "西武" },
  ],
  "2026-04-08": [
    { home: "DeNA", away: "中日" },
    { home: "阪神", away: "ヤクルト" },
    { home: "広島", away: "巨人" },
    { home: "楽天", away: "日本ハム" },
    { home: "オリックス", away: "ロッテ" },
    { home: "ソフトバンク", away: "西武" },
  ],
  "2026-04-09": [
    { home: "阪神", away: "ヤクルト" },
    { home: "広島", away: "巨人" },
    { home: "楽天", away: "日本ハム" },
    { home: "オリックス", away: "ロッテ" },
    { home: "ソフトバンク", away: "西武" },
  ],
  "2026-04-10": [
    { home: "巨人", away: "ヤクルト" },
    { home: "DeNA", away: "広島" },
    { home: "中日", away: "阪神" },
    { home: "楽天", away: "オリックス" },
    { home: "西武", away: "ロッテ" },
  ],
  "2026-04-11": [
    { home: "巨人", away: "ヤクルト" },
    { home: "DeNA", away: "広島" },
    { home: "中日", away: "阪神" },
    { home: "日本ハム", away: "ソフトバンク" },
    { home: "楽天", away: "オリックス" },
    { home: "西武", away: "ロッテ" },
  ],
  "2026-04-12": [
    { home: "巨人", away: "ヤクルト" },
    { home: "DeNA", away: "広島" },
    { home: "中日", away: "阪神" },
    { home: "日本ハム", away: "ソフトバンク" },
    { home: "楽天", away: "オリックス" },
    { home: "西武", away: "ロッテ" },
  ],
  "2026-04-14": [
    { home: "ヤクルト", away: "DeNA" },
    { home: "中日", away: "広島" },
    { home: "阪神", away: "巨人" },
    { home: "ロッテ", away: "日本ハム" },
    { home: "オリックス", away: "西武" },
    { home: "ソフトバンク", away: "楽天" },
  ],
  "2026-04-15": [
    { home: "中日", away: "広島" },
    { home: "阪神", away: "巨人" },
    { home: "ロッテ", away: "日本ハム" },
    { home: "オリックス", away: "西武" },
    { home: "ソフトバンク", away: "楽天" },
  ],
  "2026-04-16": [
    { home: "ヤクルト", away: "DeNA" },
    { home: "阪神", away: "巨人" },
    { home: "ロッテ", away: "日本ハム" },
    { home: "オリックス", away: "西武" },
    { home: "ソフトバンク", away: "楽天" },
  ],
  "2026-04-17": [
    { home: "ヤクルト", away: "巨人" },
    { home: "阪神", away: "中日" },
    { home: "広島", away: "DeNA" },
    { home: "日本ハム", away: "西武" },
    { home: "楽天", away: "ロッテ" },
    { home: "ソフトバンク", away: "オリックス" },
  ],
  "2026-04-18": [
    { home: "ヤクルト", away: "巨人" },
    { home: "阪神", away: "中日" },
    { home: "広島", away: "DeNA" },
    { home: "日本ハム", away: "西武" },
    { home: "楽天", away: "ロッテ" },
    { home: "ソフトバンク", away: "オリックス" },
  ],
  "2026-04-19": [
    { home: "ヤクルト", away: "巨人" },
    { home: "阪神", away: "中日" },
    { home: "広島", away: "DeNA" },
    { home: "日本ハム", away: "西武" },
    { home: "楽天", away: "ロッテ" },
    { home: "ソフトバンク", away: "オリックス" },
  ],
  "2026-04-21": [
    { home: "巨人", away: "中日" },
    { home: "DeNA", away: "阪神" },
    { home: "広島", away: "ヤクルト" },
    { home: "日本ハム", away: "楽天" },
    { home: "西武", away: "ソフトバンク" },
    { home: "ロッテ", away: "オリックス" },
  ],
  "2026-04-22": [
    { home: "巨人", away: "中日" },
    { home: "DeNA", away: "阪神" },
    { home: "広島", away: "ヤクルト" },
    { home: "日本ハム", away: "楽天" },
    { home: "西武", away: "ソフトバンク" },
    { home: "ロッテ", away: "オリックス" },
  ],
  "2026-04-23": [
    { home: "DeNA", away: "阪神" },
    { home: "広島", away: "ヤクルト" },
    { home: "日本ハム", away: "楽天" },
    { home: "西武", away: "ソフトバンク" },
    { home: "ロッテ", away: "オリックス" },
  ],
  "2026-04-24": [
    { home: "DeNA", away: "巨人" },
    { home: "中日", away: "ヤクルト" },
    { home: "オリックス", away: "日本ハム" },
  ],
  "2026-04-25": [
    { home: "DeNA", away: "巨人" },
    { home: "中日", away: "ヤクルト" },
    { home: "阪神", away: "広島" },
    { home: "楽天", away: "西武" },
    { home: "オリックス", away: "日本ハム" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-04-26": [
    { home: "DeNA", away: "巨人" },
    { home: "中日", away: "ヤクルト" },
    { home: "阪神", away: "広島" },
    { home: "楽天", away: "西武" },
    { home: "オリックス", away: "日本ハム" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-04-28": [
    { home: "巨人", away: "広島" },
    { home: "ヤクルト", away: "阪神" },
    { home: "中日", away: "DeNA" },
    { home: "西武", away: "日本ハム" },
    { home: "ロッテ", away: "楽天" },
    { home: "オリックス", away: "ソフトバンク" },
  ],
  "2026-04-29": [
    { home: "巨人", away: "広島" },
    { home: "ヤクルト", away: "阪神" },
    { home: "中日", away: "DeNA" },
    { home: "西武", away: "日本ハム" },
    { home: "ロッテ", away: "楽天" },
    { home: "オリックス", away: "ソフトバンク" },
  ],
  "2026-04-30": [
    { home: "巨人", away: "広島" },
    { home: "ヤクルト", away: "阪神" },
    { home: "中日", away: "DeNA" },
    { home: "西武", away: "日本ハム" },
  ],

  // ─── 5月 ────────────────────────────────────────────────────────────────
  "2026-05-01": [
    { home: "ヤクルト", away: "DeNA" },
    { home: "阪神", away: "巨人" },
    { home: "広島", away: "中日" },
    { home: "日本ハム", away: "オリックス" },
    { home: "ロッテ", away: "西武" },
    { home: "ソフトバンク", away: "楽天" },
  ],
  "2026-05-02": [
    { home: "ヤクルト", away: "DeNA" },
    { home: "阪神", away: "巨人" },
    { home: "広島", away: "中日" },
    { home: "日本ハム", away: "オリックス" },
    { home: "ロッテ", away: "西武" },
    { home: "ソフトバンク", away: "楽天" },
  ],
  "2026-05-03": [
    { home: "ヤクルト", away: "DeNA" },
    { home: "阪神", away: "巨人" },
    { home: "日本ハム", away: "オリックス" },
    { home: "ロッテ", away: "西武" },
    { home: "ソフトバンク", away: "楽天" },
  ],
  "2026-05-04": [
    { home: "巨人", away: "ヤクルト" },
    { home: "DeNA", away: "広島" },
    { home: "中日", away: "阪神" },
    { home: "楽天", away: "日本ハム" },
    { home: "西武", away: "ソフトバンク" },
    { home: "オリックス", away: "ロッテ" },
  ],
  "2026-05-05": [
    { home: "巨人", away: "ヤクルト" },
    { home: "DeNA", away: "広島" },
    { home: "中日", away: "阪神" },
    { home: "楽天", away: "日本ハム" },
    { home: "西武", away: "ソフトバンク" },
    { home: "オリックス", away: "ロッテ" },
  ],
  "2026-05-06": [
    { home: "巨人", away: "ヤクルト" },
    { home: "DeNA", away: "広島" },
    { home: "中日", away: "阪神" },
    { home: "楽天", away: "日本ハム" },
    { home: "西武", away: "ソフトバンク" },
    { home: "オリックス", away: "ロッテ" },
  ],
  "2026-05-08": [
    { home: "中日", away: "巨人" },
    { home: "阪神", away: "DeNA" },
    { home: "広島", away: "ヤクルト" },
    { home: "西武", away: "楽天" },
    { home: "オリックス", away: "日本ハム" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-05-09": [
    { home: "中日", away: "巨人" },
    { home: "阪神", away: "DeNA" },
    { home: "広島", away: "ヤクルト" },
    { home: "西武", away: "楽天" },
    { home: "オリックス", away: "日本ハム" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-05-10": [
    { home: "中日", away: "巨人" },
    { home: "阪神", away: "DeNA" },
    { home: "広島", away: "ヤクルト" },
    { home: "西武", away: "楽天" },
    { home: "オリックス", away: "日本ハム" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-05-12": [
    { home: "巨人", away: "広島" },
    { home: "ヤクルト", away: "阪神" },
    { home: "DeNA", away: "中日" },
    { home: "楽天", away: "オリックス" },
    { home: "ロッテ", away: "日本ハム" },
    { home: "ソフトバンク", away: "西武" },
  ],
  "2026-05-13": [
    { home: "巨人", away: "広島" },
    { home: "ヤクルト", away: "阪神" },
    { home: "DeNA", away: "中日" },
    { home: "ロッテ", away: "日本ハム" },
    { home: "ソフトバンク", away: "西武" },
  ],
  "2026-05-14": [
    { home: "DeNA", away: "中日" },
    { home: "楽天", away: "オリックス" },
    { home: "ロッテ", away: "日本ハム" },
  ],
  "2026-05-15": [
    { home: "巨人", away: "DeNA" },
    { home: "中日", away: "ヤクルト" },
    { home: "阪神", away: "広島" },
    { home: "日本ハム", away: "西武" },
    { home: "楽天", away: "ソフトバンク" },
    { home: "ロッテ", away: "オリックス" },
  ],
  "2026-05-16": [
    { home: "巨人", away: "DeNA" },
    { home: "中日", away: "ヤクルト" },
    { home: "阪神", away: "広島" },
    { home: "日本ハム", away: "西武" },
    { home: "楽天", away: "ソフトバンク" },
    { home: "ロッテ", away: "オリックス" },
  ],
  "2026-05-17": [
    { home: "巨人", away: "DeNA" },
    { home: "中日", away: "ヤクルト" },
    { home: "阪神", away: "広島" },
    { home: "日本ハム", away: "西武" },
    { home: "楽天", away: "ソフトバンク" },
    { home: "ロッテ", away: "オリックス" },
  ],
  "2026-05-19": [
    { home: "ヤクルト", away: "巨人" },
    { home: "阪神", away: "中日" },
    { home: "広島", away: "DeNA" },
    { home: "日本ハム", away: "楽天" },
    { home: "西武", away: "ロッテ" },
    { home: "オリックス", away: "ソフトバンク" },
  ],
  "2026-05-20": [
    { home: "阪神", away: "中日" },
    { home: "広島", away: "DeNA" },
    { home: "日本ハム", away: "楽天" },
    { home: "西武", away: "ロッテ" },
    { home: "オリックス", away: "ソフトバンク" },
  ],
  "2026-05-21": [
    { home: "ヤクルト", away: "巨人" },
    { home: "広島", away: "DeNA" },
  ],
  "2026-05-22": [
    { home: "巨人", away: "阪神" },
    { home: "中日", away: "広島" },
    { home: "楽天", away: "ロッテ" },
    { home: "西武", away: "オリックス" },
    { home: "ソフトバンク", away: "日本ハム" },
  ],
  "2026-05-23": [
    { home: "巨人", away: "阪神" },
    { home: "DeNA", away: "ヤクルト" },
    { home: "中日", away: "広島" },
    { home: "楽天", away: "ロッテ" },
    { home: "西武", away: "オリックス" },
    { home: "ソフトバンク", away: "日本ハム" },
  ],
  "2026-05-24": [
    { home: "巨人", away: "阪神" },
    { home: "DeNA", away: "ヤクルト" },
    { home: "中日", away: "広島" },
    { home: "楽天", away: "ロッテ" },
    { home: "西武", away: "オリックス" },
    { home: "ソフトバンク", away: "日本ハム" },
  ],
  "2026-05-26": [
    { home: "巨人", away: "ソフトバンク" },
    { home: "ヤクルト", away: "西武" },
    { home: "DeNA", away: "オリックス" },
    { home: "中日", away: "楽天" },
    { home: "阪神", away: "日本ハム" },
    { home: "広島", away: "ロッテ" },
  ],
  "2026-05-27": [
    { home: "巨人", away: "ソフトバンク" },
    { home: "ヤクルト", away: "西武" },
    { home: "DeNA", away: "オリックス" },
    { home: "中日", away: "楽天" },
    { home: "阪神", away: "日本ハム" },
    { home: "広島", away: "ロッテ" },
  ],
  "2026-05-28": [
    { home: "巨人", away: "ソフトバンク" },
    { home: "ヤクルト", away: "西武" },
    { home: "DeNA", away: "オリックス" },
    { home: "中日", away: "楽天" },
    { home: "阪神", away: "日本ハム" },
    { home: "広島", away: "ロッテ" },
  ],
  "2026-05-29": [
    { home: "日本ハム", away: "巨人" },
    { home: "楽天", away: "ヤクルト" },
    { home: "西武", away: "DeNA" },
    { home: "ロッテ", away: "阪神" },
    { home: "オリックス", away: "中日" },
    { home: "ソフトバンク", away: "広島" },
  ],
  "2026-05-30": [
    { home: "日本ハム", away: "巨人" },
    { home: "楽天", away: "ヤクルト" },
    { home: "西武", away: "DeNA" },
    { home: "ロッテ", away: "阪神" },
    { home: "オリックス", away: "中日" },
    { home: "ソフトバンク", away: "広島" },
  ],
  "2026-05-31": [
    { home: "日本ハム", away: "巨人" },
    { home: "楽天", away: "ヤクルト" },
    { home: "西武", away: "DeNA" },
    { home: "ロッテ", away: "阪神" },
    { home: "オリックス", away: "中日" },
    { home: "ソフトバンク", away: "広島" },
  ],

  // ─── 6月 (交流戦含む) ───────────────────────────────────────────────────
  "2026-06-02": [
    { home: "巨人", away: "オリックス" },
    { home: "ヤクルト", away: "ロッテ" },
    { home: "DeNA", away: "楽天" },
    { home: "中日", away: "ソフトバンク" },
    { home: "阪神", away: "西武" },
    { home: "広島", away: "日本ハム" },
  ],
  "2026-06-03": [
    { home: "巨人", away: "オリックス" },
    { home: "ヤクルト", away: "ロッテ" },
    { home: "DeNA", away: "楽天" },
    { home: "中日", away: "ソフトバンク" },
    { home: "阪神", away: "西武" },
    { home: "広島", away: "日本ハム" },
  ],
  "2026-06-04": [
    { home: "巨人", away: "オリックス" },
    { home: "ヤクルト", away: "ロッテ" },
    { home: "DeNA", away: "楽天" },
    { home: "中日", away: "ソフトバンク" },
    { home: "阪神", away: "西武" },
    { home: "広島", away: "日本ハム" },
  ],
  "2026-06-05": [
    { home: "巨人", away: "ロッテ" },
    { home: "ヤクルト", away: "日本ハム" },
    { home: "DeNA", away: "ソフトバンク" },
    { home: "中日", away: "西武" },
    { home: "阪神", away: "楽天" },
    { home: "広島", away: "オリックス" },
  ],
  "2026-06-06": [
    { home: "巨人", away: "ロッテ" },
    { home: "ヤクルト", away: "日本ハム" },
    { home: "DeNA", away: "ソフトバンク" },
    { home: "中日", away: "西武" },
    { home: "阪神", away: "楽天" },
    { home: "広島", away: "オリックス" },
  ],
  "2026-06-07": [
    { home: "巨人", away: "ロッテ" },
    { home: "ヤクルト", away: "日本ハム" },
    { home: "DeNA", away: "ソフトバンク" },
    { home: "中日", away: "西武" },
    { home: "阪神", away: "楽天" },
    { home: "広島", away: "オリックス" },
  ],
  "2026-06-09": [
    { home: "日本ハム", away: "DeNA" },
    { home: "楽天", away: "巨人" },
    { home: "西武", away: "広島" },
    { home: "ロッテ", away: "中日" },
    { home: "オリックス", away: "ヤクルト" },
    { home: "ソフトバンク", away: "阪神" },
  ],
  "2026-06-10": [
    { home: "日本ハム", away: "DeNA" },
    { home: "楽天", away: "巨人" },
    { home: "西武", away: "広島" },
    { home: "ロッテ", away: "中日" },
    { home: "オリックス", away: "ヤクルト" },
    { home: "ソフトバンク", away: "阪神" },
  ],
  "2026-06-11": [
    { home: "日本ハム", away: "DeNA" },
    { home: "楽天", away: "巨人" },
    { home: "西武", away: "広島" },
    { home: "ロッテ", away: "中日" },
    { home: "オリックス", away: "ヤクルト" },
    { home: "ソフトバンク", away: "阪神" },
  ],
  "2026-06-12": [
    { home: "日本ハム", away: "中日" },
    { home: "楽天", away: "広島" },
    { home: "西武", away: "巨人" },
    { home: "ロッテ", away: "DeNA" },
    { home: "オリックス", away: "阪神" },
    { home: "ソフトバンク", away: "ヤクルト" },
  ],
  "2026-06-13": [
    { home: "日本ハム", away: "中日" },
    { home: "楽天", away: "広島" },
    { home: "西武", away: "巨人" },
    { home: "ロッテ", away: "DeNA" },
    { home: "オリックス", away: "阪神" },
    { home: "ソフトバンク", away: "ヤクルト" },
  ],
  "2026-06-14": [
    { home: "日本ハム", away: "中日" },
    { home: "楽天", away: "広島" },
    { home: "西武", away: "巨人" },
    { home: "ロッテ", away: "DeNA" },
    { home: "オリックス", away: "阪神" },
    { home: "ソフトバンク", away: "ヤクルト" },
  ],
  "2026-06-19": [
    { home: "巨人", away: "中日" },
    { home: "ヤクルト", away: "広島" },
    { home: "DeNA", away: "阪神" },
    { home: "日本ハム", away: "ソフトバンク" },
    { home: "ロッテ", away: "楽天" },
    { home: "オリックス", away: "西武" },
  ],
  "2026-06-20": [
    { home: "巨人", away: "中日" },
    { home: "ヤクルト", away: "広島" },
    { home: "DeNA", away: "阪神" },
    { home: "日本ハム", away: "ソフトバンク" },
    { home: "ロッテ", away: "楽天" },
    { home: "オリックス", away: "西武" },
  ],
  "2026-06-21": [
    { home: "巨人", away: "中日" },
    { home: "ヤクルト", away: "広島" },
    { home: "DeNA", away: "阪神" },
    { home: "日本ハム", away: "ソフトバンク" },
    { home: "ロッテ", away: "楽天" },
    { home: "オリックス", away: "西武" },
  ],
  "2026-06-22": [{ home: "楽天", away: "西武" }],
  "2026-06-23": [
    { home: "中日", away: "DeNA" },
    { home: "阪神", away: "ヤクルト" },
    { home: "広島", away: "巨人" },
    { home: "日本ハム", away: "ロッテ" },
    { home: "楽天", away: "西武" },
    { home: "ソフトバンク", away: "オリックス" },
  ],
  "2026-06-24": [
    { home: "中日", away: "DeNA" },
    { home: "阪神", away: "ヤクルト" },
    { home: "広島", away: "巨人" },
    { home: "日本ハム", away: "ロッテ" },
    { home: "ソフトバンク", away: "オリックス" },
  ],
  "2026-06-25": [
    { home: "中日", away: "DeNA" },
    { home: "阪神", away: "ヤクルト" },
    { home: "楽天", away: "西武" },
    { home: "ソフトバンク", away: "オリックス" },
  ],
  "2026-06-26": [
    { home: "ヤクルト", away: "中日" },
    { home: "DeNA", away: "巨人" },
    { home: "広島", away: "阪神" },
    { home: "西武", away: "日本ハム" },
    { home: "ロッテ", away: "ソフトバンク" },
  ],
  "2026-06-27": [
    { home: "ヤクルト", away: "中日" },
    { home: "DeNA", away: "巨人" },
    { home: "広島", away: "阪神" },
    { home: "西武", away: "日本ハム" },
    { home: "ロッテ", away: "ソフトバンク" },
    { home: "オリックス", away: "楽天" },
  ],
  "2026-06-28": [
    { home: "ヤクルト", away: "中日" },
    { home: "DeNA", away: "巨人" },
    { home: "広島", away: "阪神" },
    { home: "西武", away: "日本ハム" },
    { home: "ロッテ", away: "ソフトバンク" },
    { home: "オリックス", away: "楽天" },
  ],
  "2026-06-30": [
    { home: "巨人", away: "ヤクルト" },
    { home: "DeNA", away: "広島" },
    { home: "阪神", away: "中日" },
    { home: "日本ハム", away: "オリックス" },
    { home: "楽天", away: "ロッテ" },
    { home: "ソフトバンク", away: "西武" },
  ],

  // ─── 7月 ────────────────────────────────────────────────────────────────
  "2026-07-01": [
    { home: "巨人", away: "ヤクルト" },
    { home: "阪神", away: "中日" },
    { home: "日本ハム", away: "オリックス" },
    { home: "楽天", away: "ロッテ" },
    { home: "ソフトバンク", away: "西武" },
  ],
  "2026-07-02": [
    { home: "DeNA", away: "広島" },
    { home: "阪神", away: "中日" },
    { home: "日本ハム", away: "オリックス" },
    { home: "ソフトバンク", away: "西武" },
  ],
  "2026-07-03": [
    { home: "ヤクルト", away: "DeNA" },
    { home: "中日", away: "巨人" },
    { home: "阪神", away: "広島" },
    { home: "楽天", away: "日本ハム" },
    { home: "オリックス", away: "西武" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-07-04": [
    { home: "ヤクルト", away: "DeNA" },
    { home: "中日", away: "巨人" },
    { home: "阪神", away: "広島" },
    { home: "楽天", away: "日本ハム" },
    { home: "オリックス", away: "西武" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-07-05": [
    { home: "ヤクルト", away: "DeNA" },
    { home: "中日", away: "巨人" },
    { home: "阪神", away: "広島" },
    { home: "楽天", away: "日本ハム" },
    { home: "オリックス", away: "西武" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-07-07": [
    { home: "巨人", away: "阪神" },
    { home: "DeNA", away: "中日" },
    { home: "広島", away: "ヤクルト" },
    { home: "西武", away: "楽天" },
    { home: "ロッテ", away: "日本ハム" },
    { home: "オリックス", away: "ソフトバンク" },
  ],
  "2026-07-08": [
    { home: "巨人", away: "阪神" },
    { home: "DeNA", away: "中日" },
    { home: "広島", away: "ヤクルト" },
    { home: "西武", away: "楽天" },
    { home: "ロッテ", away: "日本ハム" },
    { home: "オリックス", away: "ソフトバンク" },
  ],
  "2026-07-09": [
    { home: "巨人", away: "阪神" },
    { home: "DeNA", away: "中日" },
    { home: "広島", away: "ヤクルト" },
  ],
  "2026-07-10": [
    { home: "DeNA", away: "巨人" },
    { home: "中日", away: "広島" },
    { home: "阪神", away: "ヤクルト" },
    { home: "日本ハム", away: "西武" },
    { home: "ロッテ", away: "オリックス" },
    { home: "ソフトバンク", away: "楽天" },
  ],
  "2026-07-11": [
    { home: "DeNA", away: "巨人" },
    { home: "中日", away: "広島" },
    { home: "阪神", away: "ヤクルト" },
    { home: "日本ハム", away: "西武" },
    { home: "ロッテ", away: "オリックス" },
    { home: "ソフトバンク", away: "楽天" },
  ],
  "2026-07-12": [
    { home: "DeNA", away: "巨人" },
    { home: "中日", away: "広島" },
    { home: "阪神", away: "ヤクルト" },
    { home: "日本ハム", away: "西武" },
    { home: "ロッテ", away: "オリックス" },
    { home: "ソフトバンク", away: "楽天" },
  ],
  "2026-07-14": [
    { home: "ヤクルト", away: "巨人" },
    { home: "中日", away: "阪神" },
    { home: "広島", away: "DeNA" },
    { home: "日本ハム", away: "ソフトバンク" },
    { home: "楽天", away: "オリックス" },
    { home: "西武", away: "ロッテ" },
  ],
  "2026-07-15": [
    { home: "ヤクルト", away: "巨人" },
    { home: "中日", away: "阪神" },
    { home: "広島", away: "DeNA" },
    { home: "日本ハム", away: "ソフトバンク" },
    { home: "楽天", away: "オリックス" },
    { home: "西武", away: "ロッテ" },
  ],
  "2026-07-16": [
    { home: "ヤクルト", away: "巨人" },
    { home: "中日", away: "阪神" },
    { home: "日本ハム", away: "ソフトバンク" },
    { home: "楽天", away: "オリックス" },
    { home: "西武", away: "ロッテ" },
  ],
  "2026-07-17": [
    { home: "巨人", away: "中日" },
    { home: "DeNA", away: "ヤクルト" },
    { home: "広島", away: "阪神" },
  ],
  "2026-07-18": [
    { home: "巨人", away: "中日" },
    { home: "DeNA", away: "ヤクルト" },
    { home: "広島", away: "阪神" },
    { home: "楽天", away: "西武" },
    { home: "ロッテ", away: "ソフトバンク" },
    { home: "オリックス", away: "日本ハム" },
  ],
  "2026-07-19": [
    { home: "巨人", away: "中日" },
    { home: "DeNA", away: "ヤクルト" },
    { home: "広島", away: "阪神" },
    { home: "楽天", away: "西武" },
    { home: "ロッテ", away: "ソフトバンク" },
    { home: "オリックス", away: "日本ハム" },
  ],
  "2026-07-20": [
    { home: "巨人", away: "広島" },
    { home: "ヤクルト", away: "中日" },
    { home: "阪神", away: "DeNA" },
    { home: "楽天", away: "西武" },
    { home: "ロッテ", away: "ソフトバンク" },
    { home: "オリックス", away: "日本ハム" },
  ],
  "2026-07-21": [
    { home: "巨人", away: "広島" },
    { home: "ヤクルト", away: "中日" },
    { home: "阪神", away: "DeNA" },
    { home: "ソフトバンク", away: "オリックス" },
  ],
  "2026-07-22": [
    { home: "巨人", away: "広島" },
    { home: "ヤクルト", away: "中日" },
    { home: "阪神", away: "DeNA" },
    { home: "西武", away: "日本ハム" },
    { home: "ロッテ", away: "楽天" },
    { home: "ソフトバンク", away: "オリックス" },
  ],
  "2026-07-23": [
    { home: "西武", away: "日本ハム" },
    { home: "ロッテ", away: "楽天" },
    { home: "ソフトバンク", away: "オリックス" },
  ],
  "2026-07-24": [
    { home: "ヤクルト", away: "広島" },
    { home: "中日", away: "DeNA" },
    { home: "阪神", away: "巨人" },
    { home: "西武", away: "ソフトバンク" },
    { home: "オリックス", away: "ロッテ" },
  ],
  "2026-07-25": [
    { home: "ヤクルト", away: "広島" },
    { home: "中日", away: "DeNA" },
    { home: "阪神", away: "巨人" },
    { home: "日本ハム", away: "楽天" },
    { home: "西武", away: "ソフトバンク" },
    { home: "オリックス", away: "ロッテ" },
  ],
  "2026-07-26": [
    { home: "ヤクルト", away: "広島" },
    { home: "中日", away: "DeNA" },
    { home: "阪神", away: "巨人" },
    { home: "日本ハム", away: "楽天" },
    { home: "西武", away: "ソフトバンク" },
    { home: "オリックス", away: "ロッテ" },
  ],
  "2026-07-31": [
    { home: "巨人", away: "DeNA" },
    { home: "ヤクルト", away: "阪神" },
    { home: "広島", away: "中日" },
    { home: "日本ハム", away: "ロッテ" },
    { home: "楽天", away: "ソフトバンク" },
    { home: "西武", away: "オリックス" },
  ],

  // ─── 8月 ────────────────────────────────────────────────────────────────
  "2026-08-01": [
    { home: "巨人", away: "DeNA" },
    { home: "ヤクルト", away: "阪神" },
    { home: "広島", away: "中日" },
    { home: "日本ハム", away: "ロッテ" },
    { home: "楽天", away: "ソフトバンク" },
    { home: "西武", away: "オリックス" },
  ],
  "2026-08-02": [
    { home: "巨人", away: "DeNA" },
    { home: "ヤクルト", away: "阪神" },
    { home: "広島", away: "中日" },
    { home: "日本ハム", away: "ロッテ" },
    { home: "楽天", away: "ソフトバンク" },
    { home: "西武", away: "オリックス" },
  ],
  "2026-08-04": [
    { home: "DeNA", away: "阪神" },
    { home: "中日", away: "ヤクルト" },
    { home: "広島", away: "巨人" },
    { home: "ロッテ", away: "西武" },
    { home: "ソフトバンク", away: "日本ハム" },
  ],
  "2026-08-05": [
    { home: "DeNA", away: "阪神" },
    { home: "中日", away: "ヤクルト" },
    { home: "広島", away: "巨人" },
    { home: "ロッテ", away: "西武" },
    { home: "オリックス", away: "楽天" },
    { home: "ソフトバンク", away: "日本ハム" },
  ],
  "2026-08-06": [
    { home: "DeNA", away: "阪神" },
    { home: "中日", away: "ヤクルト" },
    { home: "広島", away: "巨人" },
    { home: "オリックス", away: "楽天" },
    { home: "ソフトバンク", away: "日本ハム" },
  ],
  "2026-08-07": [
    { home: "巨人", away: "ヤクルト" },
    { home: "DeNA", away: "広島" },
    { home: "阪神", away: "中日" },
    { home: "日本ハム", away: "楽天" },
    { home: "西武", away: "ソフトバンク" },
    { home: "ロッテ", away: "オリックス" },
  ],
  "2026-08-08": [
    { home: "巨人", away: "ヤクルト" },
    { home: "DeNA", away: "広島" },
    { home: "阪神", away: "中日" },
    { home: "日本ハム", away: "楽天" },
    { home: "西武", away: "ソフトバンク" },
    { home: "ロッテ", away: "オリックス" },
  ],
  "2026-08-09": [
    { home: "巨人", away: "ヤクルト" },
    { home: "DeNA", away: "広島" },
    { home: "阪神", away: "中日" },
    { home: "日本ハム", away: "楽天" },
    { home: "西武", away: "ソフトバンク" },
    { home: "ロッテ", away: "オリックス" },
  ],
  "2026-08-11": [
    { home: "巨人", away: "阪神" },
    { home: "ヤクルト", away: "広島" },
    { home: "中日", away: "DeNA" },
    { home: "日本ハム", away: "西武" },
    { home: "楽天", away: "オリックス" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-08-12": [
    { home: "巨人", away: "阪神" },
    { home: "ヤクルト", away: "広島" },
    { home: "中日", away: "DeNA" },
    { home: "日本ハム", away: "西武" },
    { home: "楽天", away: "オリックス" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-08-13": [
    { home: "巨人", away: "阪神" },
    { home: "ヤクルト", away: "広島" },
    { home: "中日", away: "DeNA" },
    { home: "日本ハム", away: "西武" },
    { home: "楽天", away: "オリックス" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-08-14": [
    { home: "ヤクルト", away: "DeNA" },
    { home: "中日", away: "巨人" },
    { home: "広島", away: "阪神" },
    { home: "西武", away: "ロッテ" },
    { home: "オリックス", away: "日本ハム" },
    { home: "ソフトバンク", away: "楽天" },
  ],
  "2026-08-15": [
    { home: "ヤクルト", away: "DeNA" },
    { home: "中日", away: "巨人" },
    { home: "広島", away: "阪神" },
    { home: "西武", away: "ロッテ" },
    { home: "オリックス", away: "日本ハム" },
    { home: "ソフトバンク", away: "楽天" },
  ],
  "2026-08-16": [
    { home: "ヤクルト", away: "DeNA" },
    { home: "中日", away: "巨人" },
    { home: "広島", away: "阪神" },
    { home: "西武", away: "ロッテ" },
    { home: "オリックス", away: "日本ハム" },
    { home: "ソフトバンク", away: "楽天" },
  ],
  "2026-08-18": [
    { home: "DeNA", away: "巨人" },
    { home: "阪神", away: "ヤクルト" },
    { home: "広島", away: "中日" },
    { home: "日本ハム", away: "ソフトバンク" },
    { home: "楽天", away: "ロッテ" },
    { home: "西武", away: "オリックス" },
  ],
  "2026-08-19": [
    { home: "DeNA", away: "巨人" },
    { home: "阪神", away: "ヤクルト" },
    { home: "広島", away: "中日" },
    { home: "日本ハム", away: "ソフトバンク" },
    { home: "楽天", away: "ロッテ" },
    { home: "西武", away: "オリックス" },
  ],
  "2026-08-20": [
    { home: "DeNA", away: "巨人" },
    { home: "阪神", away: "ヤクルト" },
    { home: "広島", away: "中日" },
    { home: "日本ハム", away: "ソフトバンク" },
    { home: "楽天", away: "ロッテ" },
    { home: "西武", away: "オリックス" },
  ],
  "2026-08-21": [
    { home: "巨人", away: "広島" },
    { home: "DeNA", away: "阪神" },
    { home: "中日", away: "ヤクルト" },
    { home: "楽天", away: "西武" },
    { home: "ロッテ", away: "日本ハム" },
  ],
  "2026-08-22": [
    { home: "巨人", away: "広島" },
    { home: "DeNA", away: "阪神" },
    { home: "中日", away: "ヤクルト" },
    { home: "楽天", away: "西武" },
    { home: "ロッテ", away: "日本ハム" },
    { home: "ソフトバンク", away: "オリックス" },
  ],
  "2026-08-23": [
    { home: "巨人", away: "広島" },
    { home: "DeNA", away: "阪神" },
    { home: "中日", away: "ヤクルト" },
    { home: "楽天", away: "西武" },
    { home: "ロッテ", away: "日本ハム" },
    { home: "ソフトバンク", away: "オリックス" },
  ],
  "2026-08-25": [
    { home: "ヤクルト", away: "巨人" },
    { home: "中日", away: "阪神" },
    { home: "広島", away: "DeNA" },
    { home: "西武", away: "日本ハム" },
    { home: "ロッテ", away: "ソフトバンク" },
    { home: "オリックス", away: "楽天" },
  ],
  "2026-08-26": [
    { home: "ヤクルト", away: "巨人" },
    { home: "中日", away: "阪神" },
    { home: "広島", away: "DeNA" },
    { home: "西武", away: "日本ハム" },
    { home: "ロッテ", away: "ソフトバンク" },
    { home: "オリックス", away: "楽天" },
  ],
  "2026-08-27": [
    { home: "ヤクルト", away: "巨人" },
    { home: "中日", away: "阪神" },
    { home: "広島", away: "DeNA" },
    { home: "ロッテ", away: "ソフトバンク" },
    { home: "オリックス", away: "楽天" },
  ],
  "2026-08-28": [
    { home: "DeNA", away: "中日" },
    { home: "阪神", away: "巨人" },
    { home: "広島", away: "ヤクルト" },
    { home: "日本ハム", away: "ロッテ" },
    { home: "西武", away: "楽天" },
    { home: "オリックス", away: "ソフトバンク" },
  ],
  "2026-08-29": [
    { home: "DeNA", away: "中日" },
    { home: "阪神", away: "巨人" },
    { home: "広島", away: "ヤクルト" },
    { home: "日本ハム", away: "ロッテ" },
    { home: "西武", away: "楽天" },
    { home: "オリックス", away: "ソフトバンク" },
  ],
  "2026-08-30": [
    { home: "DeNA", away: "中日" },
    { home: "阪神", away: "巨人" },
    { home: "広島", away: "ヤクルト" },
    { home: "日本ハム", away: "ロッテ" },
    { home: "西武", away: "楽天" },
    { home: "オリックス", away: "ソフトバンク" },
  ],

  // ─── 9月 ────────────────────────────────────────────────────────────────
  "2026-09-01": [
    { home: "巨人", away: "DeNA" },
    { home: "ヤクルト", away: "阪神" },
    { home: "中日", away: "広島" },
    { home: "日本ハム", away: "ソフトバンク" },
    { home: "楽天", away: "オリックス" },
    { home: "ロッテ", away: "西武" },
  ],
  "2026-09-02": [
    { home: "巨人", away: "DeNA" },
    { home: "ヤクルト", away: "阪神" },
    { home: "中日", away: "広島" },
    { home: "日本ハム", away: "ソフトバンク" },
    { home: "楽天", away: "オリックス" },
    { home: "ロッテ", away: "西武" },
  ],
  "2026-09-03": [
    { home: "ヤクルト", away: "阪神" },
    { home: "中日", away: "広島" },
  ],
  "2026-09-04": [
    { home: "ヤクルト", away: "中日" },
    { home: "広島", away: "巨人" },
    { home: "楽天", away: "日本ハム" },
    { home: "オリックス", away: "ロッテ" },
    { home: "ソフトバンク", away: "西武" },
  ],
  "2026-09-05": [
    { home: "ヤクルト", away: "中日" },
    { home: "阪神", away: "DeNA" },
    { home: "広島", away: "巨人" },
    { home: "楽天", away: "日本ハム" },
    { home: "オリックス", away: "ロッテ" },
    { home: "ソフトバンク", away: "西武" },
  ],
  "2026-09-06": [
    { home: "ヤクルト", away: "中日" },
    { home: "阪神", away: "DeNA" },
    { home: "広島", away: "巨人" },
    { home: "楽天", away: "日本ハム" },
    { home: "オリックス", away: "ロッテ" },
    { home: "ソフトバンク", away: "西武" },
  ],
  "2026-09-08": [
    { home: "巨人", away: "中日" },
    { home: "DeNA", away: "ヤクルト" },
    { home: "阪神", away: "広島" },
    { home: "ロッテ", away: "楽天" },
    { home: "オリックス", away: "西武" },
    { home: "ソフトバンク", away: "日本ハム" },
  ],
  "2026-09-09": [
    { home: "巨人", away: "中日" },
    { home: "DeNA", away: "ヤクルト" },
    { home: "阪神", away: "広島" },
    { home: "ロッテ", away: "楽天" },
    { home: "オリックス", away: "西武" },
    { home: "ソフトバンク", away: "日本ハム" },
  ],
  "2026-09-10": [
    { home: "巨人", away: "中日" },
    { home: "DeNA", away: "ヤクルト" },
    { home: "阪神", away: "広島" },
    { home: "ロッテ", away: "楽天" },
    { home: "オリックス", away: "西武" },
    { home: "ソフトバンク", away: "日本ハム" },
  ],
  "2026-09-11": [
    { home: "広島", away: "DeNA" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-09-12": [
    { home: "巨人", away: "阪神" },
    { home: "中日", away: "ヤクルト" },
    { home: "広島", away: "DeNA" },
    { home: "西武", away: "日本ハム" },
    { home: "オリックス", away: "楽天" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-09-13": [
    { home: "ヤクルト", away: "広島" },
    { home: "DeNA", away: "巨人" },
    { home: "阪神", away: "中日" },
    { home: "西武", away: "日本ハム" },
    { home: "ソフトバンク", away: "ロッテ" },
  ],
  "2026-09-14": [
    { home: "ヤクルト", away: "広島" },
    { home: "DeNA", away: "巨人" },
    { home: "阪神", away: "中日" },
  ],
  "2026-09-15": [
    { home: "日本ハム", away: "ロッテ" },
    { home: "楽天", away: "西武" },
    { home: "オリックス", away: "ソフトバンク" },
  ],
  "2026-09-16": [
    { home: "ロッテ", away: "楽天" },
    { home: "オリックス", away: "ソフトバンク" },
  ],
  "2026-09-17": [
    { home: "日本ハム", away: "西武" },
    { home: "ロッテ", away: "楽天" },
    { home: "オリックス", away: "ソフトバンク" },
  ],
  "2026-09-18": [
    { home: "巨人", away: "中日" },
    { home: "DeNA", away: "ヤクルト" },
    { home: "阪神", away: "広島" },
  ],
  "2026-09-19": [
    { home: "巨人", away: "中日" },
    { home: "DeNA", away: "ヤクルト" },
    { home: "阪神", away: "広島" },
    { home: "日本ハム", away: "オリックス" },
    { home: "楽天", away: "ソフトバンク" },
    { home: "ロッテ", away: "西武" },
  ],
  "2026-09-20": [
    { home: "巨人", away: "ヤクルト" },
    { home: "中日", away: "広島" },
    { home: "阪神", away: "DeNA" },
    { home: "日本ハム", away: "オリックス" },
    { home: "楽天", away: "ソフトバンク" },
    { home: "ロッテ", away: "西武" },
  ],
  "2026-09-21": [
    { home: "中日", away: "広島" },
    { home: "阪神", away: "DeNA" },
    { home: "日本ハム", away: "オリックス" },
    { home: "楽天", away: "ソフトバンク" },
    { home: "ロッテ", away: "西武" },
  ],
  "2026-09-22": [
    { home: "ヤクルト", away: "阪神" },
    { home: "DeNA", away: "中日" },
    { home: "広島", away: "巨人" },
    { home: "日本ハム", away: "楽天" },
    { home: "ロッテ", away: "オリックス" },
    { home: "ソフトバンク", away: "西武" },
  ],
  "2026-09-23": [
    { home: "ヤクルト", away: "阪神" },
    { home: "DeNA", away: "中日" },
    { home: "広島", away: "巨人" },
    { home: "日本ハム", away: "楽天" },
    { home: "ロッテ", away: "オリックス" },
    { home: "ソフトバンク", away: "西武" },
  ],
  "2026-09-24": [{ home: "日本ハム", away: "楽天" }],
  "2026-09-25": [
    { home: "西武", away: "ロッテ" },
    { home: "オリックス", away: "ソフトバンク" },
  ],
  "2026-09-26": [
    { home: "西武", away: "ロッテ" },
    { home: "オリックス", away: "日本ハム" },
    { home: "ソフトバンク", away: "楽天" },
  ],
  "2026-09-27": [
    { home: "西武", away: "楽天" },
    { home: "ロッテ", away: "日本ハム" },
    { home: "ソフトバンク", away: "オリックス" },
  ],
  "2026-09-28": [
    { home: "西武", away: "楽天" },
    { home: "ロッテ", away: "日本ハム" },
  ],
  "2026-09-29": [
    { home: "楽天", away: "ロッテ" },
    { home: "西武", away: "オリックス" },
  ],
  "2026-09-30": [{ home: "楽天", away: "ロッテ" }],

  // ─── 10月 (CS / 日本シリーズ) ───────────────────────────────────────────
  // 対戦カードは順位確定後に決まるため、空のまま。
  // 必要になったら手動で追加してください。
});

/**
 * 指定日の試合カード配列を返す。データなしなら空配列。
 *
 * @param {string} yyyyMmDd  — "2026-05-31" 形式
 * @returns {{ home: string, away: string }[]}
 */
export function gamesOn(yyyyMmDd) {
  return NPB_SCHEDULE[yyyyMmDd] || [];
}

/**
 * Date オブジェクトから JST の "yyyy-mm-dd" キーを生成。
 * @param {Date} date
 * @returns {string}
 */
export function dateKey(date) {
  const jst = new Date(date.getTime() + 9 * 60 * 60 * 1000);
  const y = jst.getUTCFullYear();
  const m = String(jst.getUTCMonth() + 1).padStart(2, "0");
  const d = String(jst.getUTCDate()).padStart(2, "0");
  return `${y}-${m}-${d}`;
}
